### ISSUE TITLE
This channel is not responding.

### ISSUE THREAD

**Issue by gfvirga** [plexinc-plugins/Food-Network.bundle#17]
Hello,

I am getting "This channel is not responding." After selecting a "Full Episodes" -> "Show name". Is this a known issue?

Thank you

**Comment by shopgirl284** [comment]
Considering there have been several updates to the channel plugin since this post, this issue is no longer relevant and should be closed.

**Comment by sander1** [comment]
Correct. If the issue is still present, make _sure_ you have a PMS version 1+ (older versions do not automatically update certain parts of Plex). If this is still an issue, please create an new issue and add log files of the channel (https://support.plex.tv/hc/en-us/articles/201106148-Channel-Log-Files) + `com.plexapp.system.log`.
