### ISSUE TITLE
Videos

### ISSUE THREAD

**Issue by brandumb** [plexinc-plugins/Food-Network.bundle#8]
The channel is no longer pulling any videos off the website to the plex server.

**Comment by Dude4Linux** [comment]
The Food-Network bundle was working for us until recently (several weeks ago).  It appears that they made a change on the website so that the links to the videos are not found.  All of the channels are found and the episodes and graphics are correct, but always get the error "Sorry, but we can't play this video...".  The episodes are still viewable by browser on the website.  They are now running commercials at the start of each episode, so this may be interfering.

**Comment by sander1** [comment]
This issue should be fixed with https://github.com/plexinc-plugins/Services.bundle/commit/b55b091c530ae14fa4aa9548521dd76d50324dbe Please reopen this issue if you're still having problems. Thanks!

**Comment by Dude4Linux** [comment]
Thanks, that worked great.
